export const LIST_PROJECTS_REQUEST = 'LIST_PROJECTS_REQUEST'
export const LIST_PROJECTS_SUCCESS = 'LIST_PROJECTS_SUCCESS'
export const LIST_PROJECTS_FAIL = 'LIST_PROJECTS_FAIL'

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL'

export const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_FAIL = 'EDIT_PROJECT_FAIL'

